<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="LBoL.Core"><HintPath>D:\riderProject\hextech\obj\Release\netstandard2.1\PublicizedAssemblies\LBoL.Core.243A3E060BF2F5F9ABF4F61F2E446F24\LBoL.Core.dll</HintPath></Reference>
    <Reference Include="LBoL.Base"><HintPath>D:\riderProject\hextech\obj\Release\netstandard2.1\PublicizedAssemblies\LBoL.Base.38D3FD615567EC89012AB19ACDBC2DE7\LBoL.Base.dll</HintPath></Reference>
  </ItemGroup>
</Project>
